global:
  scrape_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  - job_name: nginx
    static_configs:
      - targets: 
          - nginx-exporter:9113

rule_files:
  - ./rules/*.yml
